apiVersion: v1 
kind: PersistentVolume
metadata:
  name: efs-static 
spec:
  accesModes:
  - ReadWriteonce
  capacity:
    storage: 5Gi
  voulmeMode: FileSystem
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: 
---
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: efs-static
spec:
  accesModes:
  - ReadWriteonce
  volumeName:
    name: efs-static 
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx
  labels:
    purpose: demo
    component: nginx
spec:
 replicas: 1
 selector:
   matchLabels:
      purpose: demo
      component: nginx
 template:
   metadata:
      labels:
        purpose: demo
        component: nginx
   spec:
     containers:
     - name: nginx
       image: nginx
       volumeMounts:
       - name: efs-storage
         mountPath: /usr/share/nginx/html
     volumes:
     - name: efs-storage
       PersistentVolumeClaim:
          claimName: efs-static
        
---
apiVersion: v1 
kind: Service
metadata:
  name: nginx-svc 
spec:
  selector:
    purpose: demo
    component: nginx
  ports:
  - protocol: TCP 
    port: 80
    targetPort: 80     

