apiVersion: v1 
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  accesModes:
  - ReadWriteonce
  capacity:
    storage: 20Gi
  csi:
   driver: ebs.csi.aws.com
   fsType: ext4
   voulmeHandle: 
---
apiVersion: v1 
kind: PersistantVoulmeClaim
metadata:
  name: ebs-static
spec:
  voulmeName:
    name: ebs-static
    accesModes:
    - ReadWriteonce
    resources:
      requests:
        storage: 5Gi 
---
apiVersion: apps/v1 
kind: pod 
metadata:
  name: nginx
spec:
 containers:
 - name: nginx
   image: nginx
   volumeMounts:
   - name: ebs-storage
     mountPath: /usr/share/nginx/html
 volumes:
 - name: ebs-storage
   persistentVolumeClaim:
     claimName: ebs-static